services:
  co-atc:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: co-atc
    restart: unless-stopped
    
    ports:
      - "8000:8080"
      - "8001:8081"
      - "8002:8082"
      - "8003:8083"
      - "8004:8084"
    
    volumes:
      # Data persistence
      - co-atc-data:/app/data
      - co-atc-logs:/app/logs
      
      # Configuration (mount your customized config.toml here)
      - ./config.toml:/app/configs/config.toml:ro
      
      # Assets (REQUIRED - contains prompts, airlines, airports, runways data)
      - ../assets:/app/assets:ro
      
      # Web files (optional override for development)
      - ../www:/app/www:ro
    
    environment:
      # Timezone setting
      - TZ=America/Toronto
      
      # Go application settings
      - GO_ENV=production
      - CGO_ENABLED=0
      
      # Optional: Override config file path
      - CONFIG_PATH=/app/configs/config.toml
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    
    # Network settings
    networks:
      - co-atc-network
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

networks:
  co-atc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  co-atc-data:
    driver: local
  co-atc-logs:
    driver: local 